// 30のテスト観点データ（テスト観点.pdf より）
const PERSPECTIVES = [
  {
    no: 1,
    name: '同値の観点',
    content: '処理が同じとみなせるグループの代表値を用いる',
    technique: '同値分割',
    techniqueCodes: ['equivalence'],
  },
  {
    no: 2,
    name: '境界値の観点',
    content: '処理が異なるグループの境界値を用いる',
    technique: '境界値分析',
    techniqueCodes: ['boundary'],
  },
  {
    no: 3,
    name: '状態の観点',
    content: '状態の遷移が伴う動作',
    technique: '状態遷移テスト',
    techniqueCodes: ['state'],
  },
  {
    no: 4,
    name: '優先の観点',
    content: '処理に優先度が関係する動作',
    technique: 'デシジョンテーブル',
    techniqueCodes: ['decision'],
  },
  {
    no: 5,
    name: '時間の観点',
    content: '日付・時刻・時間が関係する動作',
    technique: '-',
    techniqueCodes: ['boundary', 'equivalence'],
  },
  {
    no: 6,
    name: '資源の観点',
    content: '限られた資源を最大限まで使用する',
    technique: '-',
    techniqueCodes: ['boundary'],
  },
  {
    no: 7,
    name: '論理の観点',
    content: '複雑な論理が関係する',
    technique: 'デシジョンテーブル',
    techniqueCodes: ['decision', 'causeeffect'],
  },
  {
    no: 8,
    name: '組み合わせの観点',
    content: 'いくつかの機能や要因の組み合わせ',
    technique: '組み合わせテスト',
    techniqueCodes: ['allpairs', 'orthogonal'],
  },
  {
    no: 9,
    name: 'タイミングの観点',
    content: 'イベントの同時発生などタイミングが関係する',
    technique: 'タイミングテスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 10,
    name: '中断の観点',
    content: '操作などを途中で取りやめるテスト',
    technique: 'エラー推測',
    techniqueCodes: ['error'],
  },
  {
    no: 11,
    name: '繰り返しの観点',
    content: '同じ操作を何度も繰り返す',
    technique: '繰り返しテスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 12,
    name: '順序の観点',
    content: '処理の待ち合わせによる処理順序が関係する動作',
    technique: '-',
    techniqueCodes: ['scenario', 'state'],
  },
  {
    no: 13,
    name: '競合の観点',
    content: '同じ資源の奪い合いが起きる動作',
    technique: '-',
    techniqueCodes: ['scenario'],
  },
  {
    no: 14,
    name: '例外の観点',
    content: '例外的な条件での動作',
    technique: 'エラー推測',
    techniqueCodes: ['error', 'abnormal'],
  },
  {
    no: 15,
    name: '割り込みの観点',
    content: '機能が動作中に別機能を動作させる',
    technique: '機能複合テスト',
    techniqueCodes: ['scenario', 'error'],
  },
  {
    no: 16,
    name: '同時動作の観点',
    content: '機能が動作中に別機能を同時に動作させる',
    technique: '機能複合テスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 17,
    name: '移行動作の観点',
    content: 'ある機能を操作中に可能な別機能の操作に移行する',
    technique: '機能複合テスト',
    techniqueCodes: ['scenario', 'state'],
  },
  {
    no: 18,
    name: '異常入力の観点',
    content: '規定外の入力を与える',
    technique: 'エラー推測',
    techniqueCodes: ['error', 'abnormal'],
  },
  {
    no: 19,
    name: '動作しない観点',
    content: '機能が動作しない条件で行う',
    technique: '無効値テスト',
    techniqueCodes: ['equivalence', 'error'],
  },
  {
    no: 20,
    name: '矛盾設定の観点',
    content: '矛盾した設定を行って動作させる',
    technique: 'エラー推測',
    techniqueCodes: ['error', 'decision'],
  },
  {
    no: 21,
    name: '切断再接続の観点',
    content: '動作中に強制的にケーブルを切断、その後再接続する',
    technique: 'エラー推測',
    techniqueCodes: ['error'],
  },
  {
    no: 22,
    name: '負荷の観点',
    content: 'システムに高い負荷をかける',
    technique: '負荷テスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 23,
    name: '性能の観点',
    content: 'システムの性能を測定する',
    technique: '性能テスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 24,
    name: 'ユーザの観点',
    content: 'ユーザの利用シーンを想定する',
    technique: 'シナリオテスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 25,
    name: 'セキュリティの観点',
    content: 'システムのセキュリティに関するテスト',
    technique: 'セキュリティテスト',
    techniqueCodes: ['abnormal', 'error'],
  },
  {
    no: 26,
    name: '構成の観点',
    content: '動作するソフトウェアの構成、ハードウェア構成など',
    technique: '構成テスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 27,
    name: 'ユーザビリティの観点',
    content: 'ユーザの使い勝手に関するテスト',
    technique: 'ユーザビリティテスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 28,
    name: '保守の観点',
    content: 'データ設定、データ変換、リモートメンテナンスなど',
    technique: '保守性テスト',
    techniqueCodes: ['scenario'],
  },
  {
    no: 29,
    name: 'プライバシーの観点',
    content: '個人情報保護の対象となるユーザデータの扱い',
    technique: 'プライバシーテスト',
    techniqueCodes: ['scenario', 'error'],
  },
  {
    no: 30,
    name: '意地悪の観点',
    content: '意地悪でキーの連打などシステムへの異常操作を行う',
    technique: '意地悪テスト',
    techniqueCodes: ['error', 'abnormal'],
  },
];

module.exports = { PERSPECTIVES };
